##############################################################################
# File:    Makefile
# Author:  Daniel Luchaup
# Date:    1 December 2013
# Copyright 2007-2013 Daniel Luchaup luchaup@cs.wisc.edu
#
# This file contains unpublished confidential proprietary work of
# Daniel Luchaup, Department of Computer Sciences, University of
# Wisconsin--Madison.  No use of any sort, including execution, modification,
# copying, storage, distribution, or reverse engineering is permitted without
# the express written consent (for each kind of use) of Daniel Luchaup.
#
##############################################################################

include ../Makefile.exG

# DO NOT DELETE
